options:
  http-port:
    type: int
    default: 80
    description: "HTTP listen port for chosen JEE container"
  bundles-dir:
    type: string
    default: "/opt/syncope/bundles"
    description: "ConnId bundles directory"
  log-dir:
    type: string
    default: "/opt/syncope/log"
    description: "Syncope log directory"
