#!/bin/bash
set -eu
source inc/common

# Generate and build Maven overlay project (if not already available)

add-apt-repository -y ppa:natecarlson/maven3
apt-get update
apt-get install -y maven3 gnupg
juju-log "Maven 3 installed"

if [ ! -d "$BASE_SRC/$PROJECT_NAME" ]; then
    cd $BASE_SRC
    $M2_HOME/bin/mvn archetype:generate \
	-DarchetypeGroupId=org.apache.syncope \
	-DarchetypeArtifactId=syncope-archetype \
	-DarchetypeRepository=http://repo1.maven.org/maven2 \
	-DarchetypeVersion=1.1.6 \
	-DgroupId=net.tirasa.syncope \
	-DartifactId=$PROJECT_NAME \
	-Dversion=1.0-SNAPSHOT \
	-DsecretKey=1apache2syncope3tirasa \
	-DinteractiveMode=false
    juju-log "Apache Syncope overlay project created under $BASE_SRC/$PROJECT_NAME"

    cd $PROJECT_NAME
    $M2_HOME/bin/mvn clean package
    juju-log "Apache Syncope overlay project successfully built"
else
    juju-log "Apache Syncope overlay project already present"
fi
